#!/bin/bash
### Job name
#PBS -N TimingOpteron4

### Mail to user
#PBS -m ae

### Queue name (small, medium, long, verylong)
#PBS -q medium

### Number of nodes 
#PBS -l nodes=1:opteron4:ppn=4

# This job's working directory
cd $PBS_O_WORKDIR

# Some informational messages
echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo This jobs runs on the following processors:
cat $PBS_NODEFILE
echo Python executable: `which asap-python`

asap-python OfficialTiming.py -t
asap-python OfficialTiming.py

