#!/bin/sh
### Job name
#PBS -N AsapS50Timing

### Mail to user
#PBS -m ae

### Queue name (small, medium, long, verylong)
#PBS -q medium

### Number of nodes (node property ev67 wanted)
#PBS -l nodes=1:s50

# This job's working directory
cd $PBS_O_WORKDIR

# Some informational messages
echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo This jobs runs on the following processors:
cat $PBS_NODEFILE
echo Python executable: `which python`
echo LD_LIBRARY_PATH is $LD_LIBRARY_PATH

python OfficialTiming.py

