#!/bin/bash
### Job name
#PBS -N AsapNehalemTiming

### Mail to user
#PBS -m ae

### Queue name (small, medium, long, verylong)
#PBS -q medium

### Number of nodes 
#PBS -l nodes=1:ppn=8

# This job's working directory
cd $PBS_O_WORKDIR

# Some informational messages
echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo This jobs runs on the following processors:
cat $PBS_NODEFILE
echo Python executable: `which python`

for i in 1 2 3 4 5 6 7 8; do
    mkdir $i
    (cd $i; python ../OfficialTiming.py) &
done

wait


