#!/bin/bash
### Job name
#PBS -N Time2011Xeon16

### Mail to user
#PBS -m ae

### Queue name (small, medium, long, verylong)
#PBS -q medium

### Number of nodes 
#PBS -l nodes=1:xeon16:ppn=16

# This job's working directory
cd $PBS_O_WORKDIR

# Some informational messages
echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo This jobs runs on the following processors:
cat $PBS_NODEFILE
echo Python executable: `which python`

python TimingEMT2013.py -t
python TimingEMT2013.py

python Timing.py -t
python Timing.py

