
// version.cpp
//
// This file is AUTOMATICALLY GENERATED BY recordversion.py.  DO NOT EDIT!
//

#include "AsapNamespace.h"
#include <string>
using std::string;

namespace ASAPSPACE {

string GetVersion()
{
  return "ASAP version 3.8.4 serial, compiled 2016-07-15 20:52 on apaar-VPCEB34EN using 'distutils'";
}

string GetShortVersion()
{
  return "3.8.4";
}

} // end namespace

